<?php
$values = $session ?? [];
$intervals = $values['intervals'] ?? [['repeat_count'=>1,'distance_m'=>'','style'=>'','intensity'=>'','rest_seconds'=>'','note'=>'']];
$today = (new DateTimeImmutable('now', new DateTimeZone((string) $user['timezone'])))->format('Y-m-d');
?>
<form method="post" action="<?= e($formAction) ?>" class="stack-form card swimming-form" data-swimming-form data-mode="<?= $isEdit ? 'edit' : 'create' ?>" data-swimming-id="<?= $isEdit ? (int)$values['id'] : '' ?>" data-user-id="<?= (int)$user['id'] ?>">
    <input type="hidden" name="_csrf" value="<?= e(\App\Core\Csrf::token()) ?>"><?php if($isEdit): ?><input type="hidden" name="version" value="<?= (int)$values['version'] ?>"><?php endif; ?>
    <div class="swim-save-state" data-swim-save-state role="status">Черновик сохраняется на этом устройстве</div>
    <div class="field-grid">
        <label>Дата<input type="date" name="swim_date" value="<?= e($values['swim_date'] ?? $today) ?>" required></label><label>Из расписания<select name="schedule_id"><option value="">Вручную</option><?php foreach($schedule as $row): ?><option value="<?= (int)$row['id'] ?>" <?= (int)($values['schedule_id'] ?? 0)===(int)$row['id']?'selected':'' ?>><?= e($row['label']) ?> · <?= ['','Пн','Вт','Ср','Чт','Пт','Сб','Вс'][(int)$row['weekday']] ?></option><?php endforeach; ?></select></label>
        <label>Длительность, мин<input type="number" name="duration_minutes" min="1" max="1440" value="<?= e($values['duration_minutes'] ?? '') ?>" required></label><label>Длина бассейна, м<input type="number" name="pool_length_m" min="10" max="100" value="<?= e($values['pool_length_m'] ?? 25) ?>" required></label><label>Общая дистанция, м<input type="number" name="total_distance_m" min="10" max="100000" value="<?= e($values['total_distance_m'] ?? '') ?>" required></label><label>Основной стиль<input name="primary_style" maxlength="60" value="<?= e($values['primary_style'] ?? '') ?>" placeholder="Кроль" required></label>
        <label>Интенсивность 1–10<input type="number" name="intensity" min="1" max="10" value="<?= e($values['intensity'] ?? '') ?>" required></label><label>Самочувствие 1–5<input type="number" name="wellbeing" min="1" max="5" value="<?= e($values['wellbeing'] ?? '') ?>" required></label><label>Усталость рук 1–5<input type="number" name="arms_fatigue" min="1" max="5" value="<?= e($values['arms_fatigue'] ?? '') ?>" required></label><label>Усталость спины 1–5<input type="number" name="back_fatigue" min="1" max="5" value="<?= e($values['back_fatigue'] ?? '') ?>" required></label><label>Усталость ног 1–5<input type="number" name="legs_fatigue" min="1" max="5" value="<?= e($values['legs_fatigue'] ?? '') ?>" required></label>
    </div>
    <fieldset class="interval-builder"><legend>Структурированные блоки</legend><p class="muted">Сумма повторов × дистанция должна совпасть с общей дистанцией.</p><div data-interval-list><?php foreach($intervals as $index=>$interval): ?><div class="interval-row" data-interval-row><span class="interval-number"><?= (int)$index+1 ?></span><label>Повторы<input type="number" name="interval_repeat_count[]" min="1" max="100" value="<?= e($interval['repeat_count'] ?? 1) ?>" required></label><label>Метров за повтор<input type="number" name="interval_distance_m[]" min="10" max="10000" value="<?= e($interval['distance_m'] ?? '') ?>" required></label><label>Стиль<input name="interval_style[]" maxlength="60" value="<?= e($interval['style'] ?? '') ?>" required></label><label>Интенсивность<input type="number" name="interval_intensity[]" min="1" max="10" value="<?= e($interval['intensity'] ?? '') ?>"></label><label>Отдых, сек<input type="number" name="interval_rest_seconds[]" min="0" max="3600" value="<?= e($interval['rest_seconds'] ?? '') ?>"></label><label class="interval-note">Заметка<input name="interval_note[]" maxlength="500" value="<?= e($interval['note'] ?? '') ?>"></label><button class="icon-button interval-remove" type="button" data-remove-interval aria-label="Удалить блок">×</button></div><?php endforeach; ?></div><button class="button button-quiet" type="button" data-add-interval>＋ Добавить блок</button><strong class="interval-total" data-interval-total>В блоках: 0 м</strong></fieldset>
    <label>Комментарий<textarea name="comment" maxlength="2000"><?= e($values['comment'] ?? '') ?></textarea></label><button class="button button-primary" type="submit"><?= $isEdit ? 'Сохранить изменения' : 'Сохранить плавание' ?></button>
</form>
