<?php

declare(strict_types=1);

require dirname(__DIR__) . '/bootstrap.php';

use App\Controller\AuthController;
use App\Controller\ApiController;
use App\Controller\AssistantController;
use App\Controller\SiteToolsApiController;
use App\Controller\ProgramDraftController;
use App\Controller\WorkoutInstanceController;
use App\Controller\WebController;
use App\Core\Router;

$router = new Router();
$auth = new AuthController();
$web = new WebController();
$api = new ApiController();
$assistant = new AssistantController();
$siteTools = new SiteToolsApiController();
$programDrafts = new ProgramDraftController();
$workoutInstances = new WorkoutInstanceController();

$router->add('GET', '/', [$web, 'dashboard']);
$router->add('GET', '/login', [$auth, 'loginForm']);
$router->add('POST', '/login', [$auth, 'login']);
$router->add('GET', '/register', [$auth, 'registerForm']);
$router->add('POST', '/register', [$auth, 'register']);
$router->add('POST', '/logout', [$auth, 'logout']);
$router->add('GET', '/plans/import', [$web, 'importForm']);
$router->add('POST', '/plans/import/preview', [$web, 'importPreview']);
$router->add('POST', '/plans/import/confirm', [$web, 'importConfirm']);
$router->add('POST', '/plans/import/cancel', [$web, 'importCancel']);
$router->add('GET', '/plans/{id}', [$web, 'plan']);
$router->add('POST', '/plans/{id}/reschedule', [$web, 'reschedulePlan']);
$router->add('POST', '/plans/{id}/delete', [$web, 'deletePlan']);
$router->add('GET', '/sessions/{id}', [$web, 'session']);
$router->add('POST', '/sessions/{id}/edit', [$web, 'editCompletedSession']);
$router->add('POST', '/sessions/{id}/cancel', [$web, 'cancelSession']);
$router->add('POST', '/sets/{id}/edit', [$web, 'editCompletedSet']);
$router->add('POST', '/sets/{id}/delete', [$web, 'deleteSet']);
$router->add('POST', '/progression/{id}', [$web, 'resolveProgression']);
$router->add('GET', '/export/session/{id}.{format}', [$web, 'export']);
$router->add('POST', '/api/sessions', [$api, 'start']);
$router->add('GET', '/api/sessions/{id}', [$api, 'session']);
$router->add('POST', '/api/sessions/{id}/sets', [$api, 'addSet']);
$router->add('PATCH', '/api/sets/{id}', [$api, 'updateSet']);
$router->add('PATCH', '/api/sessions/{id}/exercise-status', [$api, 'exerciseStatus']);
$router->add('PATCH', '/api/sessions/{id}/replace-exercise', [$api, 'replaceExercise']);
$router->add('POST', '/api/sessions/{id}/discomfort', [$api, 'discomfort']);
$router->add('POST', '/api/sessions/{id}/finish', [$api, 'finish']);
$router->add('GET', '/programs', [$web, 'programs']);
$router->add('GET', '/history', [$web, 'history']);
$router->add('GET', '/analytics', [$web, 'analytics']);
$router->add('GET', '/measurements', [$web, 'measurements']);
$router->add('POST', '/measurements', [$web, 'addMeasurement']);
$router->add('POST', '/measurements/{id}/delete', [$web, 'deleteMeasurement']);
$router->add('GET', '/swimming', [$web, 'swimming']);
$router->add('POST', '/swimming', [$web, 'addSwimming']);
$router->add('GET', '/swimming/{id}', [$web, 'swimmingSession']);
$router->add('POST', '/swimming/{id}/edit', [$web, 'editSwimming']);
$router->add('POST', '/swimming/{id}/delete', [$web, 'deleteSwimming']);
$router->add('GET', '/schedule', [$web, 'schedule']);
$router->add('POST', '/schedule', [$web, 'saveSchedule']);
$router->add('GET', '/export/swimming/{id}.{format}', [$web, 'exportSwimming']);
$router->add('GET', '/backup', [$web, 'backup']);
$router->add('GET', '/settings', [$web, 'settings']);
$router->add('GET', '/assistant', [$assistant, 'index']);
$router->add('POST', '/assistant/activation/confirm', [$assistant, 'confirmActivation']);
$router->add('POST', '/assistant/activation/cancel', [$assistant, 'cancelActivation']);
$router->add('POST', '/settings/theme', [$web, 'saveTheme']);
$router->add('POST', '/restore/preview', [$web, 'restorePreview']);
$router->add('POST', '/restore/confirm', [$web, 'restoreConfirm']);
$router->add('POST', '/restore/cancel', [$web, 'restoreCancel']);
$router->add('GET', '/exercises', [$web, 'exercises']);
$router->add('GET', '/exercises/{id}', [$web, 'exerciseAnalytics']);
$router->add('POST', '/exercises', [$web, 'addExercise']);
$router->add('POST', '/exercises/{id}', [$web, 'updateExercise']);
$router->add('GET', '/api/analytics/weekly', [$api, 'weekly']);
$router->add('POST', '/api/swimming', [$api, 'createSwimming']);
$router->add('GET', '/api/swimming/{id}', [$api, 'swimming']);
$router->add('PATCH', '/api/swimming/{id}', [$api, 'updateSwimming']);
$router->add('GET', '/api/assistant/profile', [$siteTools, 'profile']);
$router->add('GET', '/api/assistant/plans', [$siteTools, 'plans']);
$router->add('GET', '/api/assistant/plans/{programId}/versions', [$siteTools, 'planVersions']);
$router->add('GET', '/api/assistant/plans/{programId}/versions/{version}', [$siteTools, 'planVersion']);
$router->add('GET', '/api/assistant/plans/{programId}/templates/{templateId}', [$siteTools, 'planTemplate']);
$router->add('GET', '/api/assistant/plans/{programId}', [$siteTools, 'plan']);
$router->add('GET', '/api/assistant/workouts', [$siteTools, 'workouts']);
$router->add('GET', '/api/assistant/workouts/{workoutId}', [$siteTools, 'workout']);
$router->add('GET', '/api/assistant/sessions/{sessionId}', [$siteTools, 'session']);
$router->add('GET', '/api/assistant/exercises/search', [$siteTools, 'exerciseSearch']);
$router->add('GET', '/api/assistant/exercises/{exerciseId}/history', [$siteTools, 'exerciseHistory']);
$router->add('GET', '/api/assistant/exercises/{exerciseId}/alternatives', [$siteTools, 'exerciseAlternatives']);
$router->add('GET', '/api/assistant/progress', [$siteTools, 'progress']);
$router->add('GET', '/api/assistant/schedule/{date}', [$siteTools, 'scheduledWorkout']);
$router->add('POST', '/api/assistant/program-drafts', [$programDrafts, 'create']);
$router->add('PATCH', '/api/assistant/program-drafts/{draftId}', [$programDrafts, 'update']);
$router->add('POST', '/api/assistant/program-drafts/{draftId}/activation/prepare', [$programDrafts, 'prepareActivation']);
$router->add('POST', '/api/assistant/program-drafts/{draftId}/activation/confirm', [$programDrafts, 'confirmActivation']);
$router->add('POST', '/api/assistant/program-drafts/{draftId}/activation/cancel', [$programDrafts, 'cancelActivation']);
$router->add('PATCH', '/api/assistant/workout-instances/{instanceId}/reschedule', [$workoutInstances, 'reschedule']);
$router->add('PATCH', '/api/assistant/workout-instances/{instanceId}/replace-exercise', [$workoutInstances, 'replaceExercise']);
$router->add('GET', '/coming-soon', [$web, 'comingSoon']);

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$router->dispatch($method === 'HEAD' ? 'GET' : $method, rtrim($path, '/') ?: '/');
